apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plantuml
  name: plantuml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml
  template:
    metadata:
      labels:
        app: plantuml
    spec:
      containers:
        - image: plantuml/plantuml-server:jetty
          name: plantuml
          ports:
            - containerPort: 8080
              protocol: TCP
      hostname: plantuml
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: plantuml
  name: plantuml
spec:
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8080
      nodePort: 32003
  selector:
    app: plantuml
  type: NodePort
